export const GERAL_FILE = [
  {
    name: 'example.component.html',
    content: [
      '<form [formGroup]="form" (ngSubmit)="onSubmit()">',
      '<div>',
      '<ngx-eg-opt [time]="5" [errorMessage]="{ timeout: \'tempo excedido\', required: \'campo obrigatório\', minlength: \'mínimo de 4 dígitos\'}" formControlName="opt">',
      '</ngx-eg-opt>',
      '<div>',
      '<span>Din\'t get a code ?</span>',
      '<ngx-eg-button [type]="\'link\'" [size]="\'small\'" [disabled]="!timeout" [fill]="\'clear\'" [label]="\'resend code\'" (onClick)="resend()">',
      '</ngx-eg-button>',
      '</div>',
      '<div>',
      '<ngx-eg-timer #timer [label]="\'Seconds Left\'" [time]="5" (timeOut)="timeOut()"></ngx-eg-timer>',
      '</div>',
      '</div>',
      '<ngx-eg-button [type]="\'submit\'" [disabled]="!!form.get(\'opt\')!.errors" [label]="\'Validate\'"></ngx-eg-button>',
      '</form>'
    ]
  },
  {
    name: 'example.component.ts',
    content: [
      'import { Component } from \'@angular/core\';',
      'import { NgxEgOptInput, NgxEgTimer } from \'ngx-eg-app\';',
      'import {',
      'FormControl,',
      'FormGroup,',
      'ReactiveFormsModule,',
      'Validators',
      '} from \'@angular/forms\';',
      '',
      '@Component({',
      'selector: \'app-example\',',
      'imports: [NgxEgOptInput, NgxEgTimer, ReactiveFormsModule],',
      'templateUrl: \'./example.component.html\'',
      '})',
      'export class ExampleComponent {',
      '',
      '@ViewChild(\'timer\') public timer!: NgxEgTimer;',
      '',
      'public time = 10;',
      'public timeout = false;',
      'public form: FormGroup = new FormGroup({',
      'opt: new FormControl(\'\', [Validators.required, Validators.minLength(4)])',
      '});',
      '',
      'public timeOut(): void {',
      'this.timeout = true;',
      '}',
      '',
      'public resend(): void {',
      'this.form.reset();',
      'this.timeout = false;',
      'this.time = 10;',
      'this.timer.start();',
      '}',
      '',
      'public onSubmit(): void {',
      'console.log(this.form);',
      '}',
      '}'
    ]
  },
  {
    name: 'example.component.css',
    content: [
      'div,',
      'form {',
      'display: flex;',
      'flex-wrap: wrap;',
      'justify-content: center;',
      'align-items: center;',
      'width: 100%;',
      '}',
      '',
      'form {',
      'width: 500px;',
      'margin: auto;',
      'gap: 1rem;',
      '}',
    ]
  }
];